### ISSUE TITLE
Cake Technologies

### ISSUE THREAD

**Issue by thiwankaw** [dilumn/tldr#72]
pegging is paid after 3 month delay. From October 2022, the pegging amount is reduced per performance.  100%,90%,80%70% or 0%.   50% for interns.

**Comment by thiwankaw** [comment]
[FAQs Peg Payout Q4.pdf](https://github.com/dilumn/tldr/files/10680430/FAQs.Peg.Payout.Q4.pdf)

**Comment by dilumn** [comment]
Thanks @thiwankaw for information. I updated
